unitree_g1:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: default_checker_config.yaml

airbot_mmk2:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: default_checker_config.yaml

unitree_g1edu-u3:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: default_checker_config.yaml

yinhe:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: yinhe.yaml

agilex_cobot_decoupled_magic:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: agilex_cobot_decoupled_magic.yaml


leju_robot:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: leju_robot.yaml

galaxea_r1_lite:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: galaxea_r1_lite.yaml


ruantong_a2d:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: ruantong_a2d.yaml

realman_rmc-aiad-l:
- version: default_version
  base_config_path: default_checker_config.yaml
  specific_config_path: agilex_cobot_decoupled_magic.yaml
