# Dataset-level checkers (作用于整个数据集)
dataset_data_checkers:  #  筛选出帧数小于阈值的Episode，判定为异常Episode
  - name: "few_episode_frames"
    params:
      threshold: 150  # threshold（阈值）：默认150帧，阈值越小越容易判定为正常，越大越严格
    should_check: True  

  - name: "too_few_episodes"  # 检测数据集总有效Episode数量过少的异常
    params:
      threshold: 30  #  若数据集内有效Episode数量（排除ignored_indices）小于阈值，判定整个数据集所有Episode为异常
    should_check: True  

  - name: "abnormal_episode_length"  #  找出帧数显著偏离数据集整体分布的Episode（过短/过长），判定为异常
    params:
      threshold: 5.0  # threshold（MAD阈值）：默认4.0，值越大越宽松（更少Episode被判定为离群），值越小越严格
    should_check: True  

# Episode-level data checkers (作用于每个 episode 的数值数据，如关节角)
episode_data_checkers:
  - name: "static_frame_rate"  # 通过滑动窗口检测每个窗口是否静止，统计所有被标记为静止的帧的总占比
    params:
      window_size: 5  #  默认5帧，窗口越大越容易检测到静止（单帧抖动不影响），越小越敏感
      threshold: 0.02  #  默认0.01，值越小越更少帧被判定为静止，如果数据的标准差在这个范围内，则被认定成静止
      skipsize: 0.05  # 跳过前后5%帧的统计，最大10%,保持默认即可
    should_check: True  
    score_weight: 1.0   

  - name: "static_joint"  #  全局判断机械臂是否处于静止（足够多关节的标准差小于阈值）
    params:   
      static_joints_percent: 0.8  #  静态关节占比阈值）：默认40%，值越小越容易判定为静态，越大越宽容，需要在前面的yaml或者字段，如果是单臂操作，为0.6,双臂操作为0.4
      epsilon: 0.001  #  关节数据的标准差：每个关节的全局标准差越小，越容易被判定为静态
    should_check: True  
    score_weight: 1.0   

  - name: "motion_data_valid_frame_range"  # 通过运动数据获取该episode的有效区间
    params:
      window_size: 5  #  
      threshold: 0.02  #  
    should_check: True  
    score_weight: 1.0   

episode_video_checkers:
  - name: "max_frame_stable_then_jump_rate"  # 检测视频稳定后跳变的最大汉明距离
    should_check: True  
    score_weight: 1.0   

  - name: "max_frame_jump_dist"  #  检测视频关键帧的最大跳变距离是否超标
    should_check: True  
    params:  
      max_dist_threshold: 200  #  max_dist_threshold（跳变阈值）：默认50，超过这个数值为异常，值越小越容易判定为异常，越大越宽松
    score_weight: 1.0   

  - name: "video_color_shift_detection"  # 统计视频中相邻帧颜色差值超过阈值的帧数占比
    should_check: True                    # 启用
    params:  
      color_diff_threshold: 30.0            # color_diff_threshold（颜色差阈值）：默认30.0，值越小越容易检测到突变，越大越宽松
    score_weight: 1.0                     # 得分权重

  - name: "consecutive_static_frames"  # 检测视频中由异常因素导致的连续静止帧
    should_check: True
    params:
      phash_dist_threshold: 2    # 哈希距离阈值，可根据需求调整，越小越宽松
      static_frames_threshold: 20 # 连续静止帧数阈值，该数值暂时没有使用
      sample_count: 4
    score_weight: 1.0

  - name: "camera_resolution_consistency"  # 检查视频的分辨率与info.json中是否定义的一致
    should_check: True
    score_weight: 1.0

  - name: "video_valid_frame_range" # 通过视频数据获取该episode的有效区间
    params:
      phash_dist_threshold: 2 # 哈希距离阈值，可根据需求调整，越小越宽松
    should_check: True  
    score_weight: 1.0   
